### ISSUE TITLE
running headless

### ISSUE THREAD

**Issue by masterkain** [TrevorSundberg/puppeteer-in-electron#12] opened 2020-05-08 16:38 UTC
I'm new, trying to wrap my head around all this new stuff I'm playing with.

I'm building an electron app, I integrated `puppeteer-in-electron`.

Basically the app will download a js puppeteer task and execute it.
So far I'm using puppeteer-cluster, puppeteer-extra server-side and porting these scripts into electron.
I got many things working and I'm evaluating puppeteer-in-electron because my goal is to perform these tasks without resorting to using/configuring an external browser or requiring the end user to have one.

I have two questions:

- is there a way to run this pie in headless mode so it performs the puppeteer scripts without opening extra windows beside the electron one?
- is this the right tool for this kind of job?

thanks

**Comment by TrevorSundberg** [comment] 2020-05-09 01:07
I haven't tried to run puppeteer as headless, though I'm fairly certain they haven't implemented a headless mode:

See:
https://github.com/electron/electron/issues/228
https://medium.com/@mohamedmansour/how-to-run-electron-js-in-software-rendering-headless-49601b87961e

You could certainly try the above blog post with replacing dll/so files, however it might make more sense to recompile electron. As for whether it's the right tool, I don't really understand what it is you're trying to do so I can't answer that, but I wish you luck!

**Comment by TrevorSundberg** [comment] 2020-05-16 21:01
Closing because it's not supported by electron.

**Closed** 2020-05-16 21:00 UTC

**Comment by karlitos** [comment] 2020-09-04 21:35
Hi, isn't there really any way to run puppeteer 'headless' ?

I am working on an app, which should allow to [export rendered resumes in PDF/PNG](https://github.com/karlitos/KissMyResume/tree/electron-app).

The problem is, that electrons `printToPDF` method is just very flaky, see [here](https://github.com/electron/electron/issues/20634) and [here](https://github.com/electron/electron/issues/14705)

I was able to start the normal `puppeteer` from the _main_ process and perform the export from there, but this would also mean to bundle chromium with my app and I am getting in lot of issues with bundling and providing the path to the local binary ...

So, `puppeteer-in-electron` was looking like a win-win solution, almost perfect, but when trying the export function I got

```javascript
Error occurred in handler for 'process-cv': Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented
    at /Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:44267:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:44266:16)
    at Page.pdf (/Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:51420:43)
    at /Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:430:43
    at step (/Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:340:23)
    at Object.next (/Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:321:53)
    at fulfilled (/Users/kmacha/Dev/kiss-my-resume/.webpack/main/index.js:312:58) {
  message: 'Protocol error (Page.printToPDF): PrintToPDF is not implemented'
}```

**Comment by p8R** [comment] 2020-09-15 11:53
@karlitos Yes, you can run puppeteer in headless mode. Moreovere this is the default mode for running puppeteer:
```
const browser = await puppeteer.launch({headless: true}); // default is true; true - headless, false - browser window visible
```

**Comment by karlitos** [comment] 2020-09-16 07:24
Hello @p8R, thank you for your reply, I am not sure, if you understand me correctly. I wanted to use **puppeteer-in-electron**  in headless mode, since the Electron API does have support taking full-page screenshots and there are/were issues with reliable printing (to PDF)
